config/routes.rb
Rails.application.routes.draw do
  get 'bookings/create'

  get 'password_resets/new'

  get 'password_resets/edit'

  root  'welcome#index'

  get     '/signup',  to: 'users#new'
  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :journals,            only: [:create, :show]
  resources :bookings
  
  #get ':controller(/:action(/:id))'
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user,   only: [:edit, :update]
  before_action :valid_user, only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]    # Case (1)

  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = "Email mit Anweisungen zum zurücksetzen des Passworts wurde 
            verschickt."
      redirect_to root_url
    else
      flash.now[:danger] = "Email Adresse existiert nicht"
      render 'new'
    end
  end
  
  def edit
  
  end
  
  def update
    if params[:user][:password].empty?                  # Case (3)
      @user.errors.add(:password, "can't be empty")
      render 'edit'
    elsif @user.update_attributes(user_params)          # Case (4)
      log_in @user
      flash[:success] = "Password has been reset."
      redirect_to @user
    else
      render 'edit'                                     # Case (2)
    end
  end

  private
  
    def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end

    # Before filters

    def get_user
      @user = User.find_by(email: params[:email])
    end

    # Confirms a valid user.
    def valid_user
      unless (@user && @user.activated? &&
              @user.authenticated?(:reset, params[:id]))
        redirect_to root_url
      end
    end

    # Checks expiration of reset token.
    def check_expiration
      if @user.password_reset_expired?
        flash[:danger] = "Der Link zum zuruecksetzen des Passworts ist 
                          abgelaufen."
        redirect_to new_password_reset_url
      end
    end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<h1>Password zurücksetzen</h1>
<%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
  <p>
    <%= render 'shared/error_messages', object: f.object %>
  </p>
  <p>
    <%= hidden_field_tag :email, @user.email %>
  </p>
  <p>
    <%= f.label :password %>
  </p>
  <p>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %>
  </p>
  <p>
    <%= f.password_field :password_confirmation %>
  </p>
  <p>
    <%= f.submit "Passwort zuruecksetzen" %>
  </p>
<% end %>

app/views/password_resets/new.html.erb
<h1>Passwort vergessen</h1>
<%= form_for(:password_reset, url: password_resets_path) do |f| %>
  <p>
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </p>
  <p>
    <%= f.submit "Abschicken" %>
  </p>
<% end %>