config/routes.rb
Rails.application.routes.draw do
  get 'bookings/create'

  get 'password_resets/new'

  get 'password_resets/edit'

  root  'welcome#index'

  get     '/signup',  to: 'users#new'
  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :journals,            only: [:create, :show]
  resources :bookings
  
  #get ':controller(/:action(/:id))'
end

app/views/shared/_booking_form.html.erb
<%= form_for(@journal, url: bookings_path) do |f| %>
  <p>
    IKR Kontenrahmen
  </p>
  <p>
    <%= render 'shared/error_messages', object: f.object %>
  </p>
  <% if current_user.journals.count <= 1 %>
    <p>
      Um Ihre Buchhaltung fuehren zu koennen, muss zuerst das Eigenkapitalkonto
      aus der Eroeffnungsbilanz gebucht werden.
    </p>
    <p>
      Als weitere Schritte muessen alle Buchungen aus der Eroeffnungsbilanz
      durchgefuert werden.
    </p>
    <p>
      Die oben genannt Buchungen muessen Sie nur ein mal als neuer Kunde durchfuehren.
      Die darauf folgenden Buchungen aus der Eroeffnungsbilanz, inklusive 
      Eigenkapitalkontobuchung, werden bei darauf folgenden Jahresabschluessen 
      automatisch erstellt.
    </p>
  <% end %>
  <p>
    <%= f.text_field :buchungskreis, placeholder: "Buchungskreis" %>
    Buchungskreis
  </p>
  <p>
    <%= f.text_field :belegnummer, placeholder: "Belegnummer" %>
    Belegnummer
  </p>
  <p>
    <% if current_user.journals.count == 0 %>
      <%= f.text_field :from_account_number, :value => "8000", :readonly => true %>
    <% else %>
      <%= f.text_field :from_account_number, placeholder: "Kontonummer" %>
    <% end %>
    Soll Kontonummer
  </p>
  <p>
    <% if current_user.journals.count == 0 %>
      <%= f.text_field :from_account, :value => "Eroeffnungsbilanz", :readonly => true  %>
    <% else %>
      <%= f.text_field :from_account, placeholder: "Kontoname" %>
    <% end %>
    Soll Kontoname
  </p>
  <p>
    <%= f.text_field :from_amount, placeholder: "Betrag" %>
    Soll Betrag
  </p>
  <p>
    <% if current_user.journals.count == 0 %>
      <%= f.text_field :to_account_number, :value => "30", :readonly => true %>
    <% else %>
      <%= f.text_field :to_account_number, placeholder: "Kontonummer" %>
    <% end %>
    Haben Kontonummer
  </p>
  <p>
    <% if current_user.journals.count == 0 %>
      <%= f.text_field :to_account, :value => "Eigenkapital", :readonly => true %>
    <% else %>
      <%= f.text_field :to_account, placeholder: "Kontoname" %>
    <% end %>
    Haben Kontoname
  </p>
  <p>
    <%= f.text_field :to_amount, placeholder: "Betrag" %>
    Haben Betrag
  </p>
  <p>
    <%= f.submit "Buchen"%>
  </p>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  The form contains <%= pluralize(object.errors.count, "error") %>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li id="error_explanation"><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_journal_form_update.html.erb
<%= form_for(@journal) do |f| %>
  <p>
    <%= render 'shared/error_messages', object: f.object %>
  </p>
  <p>
    <%= f.radio_button :buchungsart, 0, :checked => false %>
    Aktive Eroeffnungsbuchung</br>
    <%= f.radio_button :buchungsart, 1, :checked => false %>
    Passive Eroeffnungsbuchung</br>
    <%= f.radio_button :buchungsart, 2, :checked => true %>
    Einfache Buchung
  </p>
  <p>
    <%= f.text_field :from_account_number, placeholder: "Kontonummer" %>
    Soll Kontonummer
  </p>
  <p>
    <%= f.text_field :from_account, placeholder: "Kontoname" %>
    Soll Kontoname
  </p>
  <p>
    <%= f.text_field :from_amount, placeholder: "Betrag" %>
    Soll Betrag
  </p>
  <p>
    <%= f.text_field :to_account_number, placeholder: "Kontonummer" %>
    Haben Kontonummer
  </p>
  <p>
    <%= f.text_field :to_account, placeholder: "Kontoname" %>
    Haben Kontoname
  </p>
  <p>
    <%= f.text_field :to_amount, placeholder: "Betrag" %>
    Haben Betrag
  </p>
  <p>
    <%= f.submit "Senden"%>
  </p>
<% end %>

app/views/shared/_user_info.html.erb
</br></br>
<%= link_to "Mein Profil anzeigen", current_user %>
<%= pluralize(current_user.journals.count, "journal") %>