config/routes.rb
Rails.application.routes.draw do
  get 'bookings/create'

  get 'password_resets/new'

  get 'password_resets/edit'

  root  'welcome#index'

  get     '/signup',  to: 'users#new'
  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :journals,            only: [:create, :show]
  resources :bookings
  
  #get ':controller(/:action(/:id))'
end

app/views/layouts/_header.html.erb
<%= link_to "Home", root_path %>
<%= link_to "Hilfe", '#' %>
<% if logged_in? %>
  <%= link_to "Buchung", new_booking_path %>
  <%= link_to "Journal", current_user %>
  <%= link_to "Hauptbuch", journal_path(current_user) %>
  <%= link_to "Jahresabschluss erstellen", booking_path(current_user) %>
  <%= link_to "Einstellungen", edit_user_path(current_user) %>
  <%= link_to "Log out", logout_path, method: "delete" %>
<% else %>
  <%= link_to "Log in", login_path %>
<% end %>
</br></br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookkeeping</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <% flash.each do |message_type, message| %>
        <%= message %>
    <% end %>
    <%= yield %>
  </body>
</html>